"""Convert dumped per-edge / S_c numerics into LaTeX \\input fragments
consumed by the TikZ figures.

Inputs (produced by dump_ieee14_edge_ranking.py and dump_sc_matrix_cora.py):
    paper/figures/data/ieee14_edges.csv
    paper/figures/data/sc_matrix.npy
    paper/figures/data/sc_v1.npy
    paper/figures/data/sc_meta.json

Outputs (\\input'd by the corresponding TikZ figures):
    paper/figures/data/ieee14_top_edges.tex   -- AEGIS top-k + GT overlay draws
    paper/figures/data/sc_heatmap_cells.tex   -- \\heatcell{c}{r}{v} lines
    paper/figures/data/sc_v1_bars.tex         -- v_1 bar definitions
    paper/figures/data/sc_meta.tex            -- \\sckmeta macros (N, sigma_1, gap)

If an input is missing, the corresponding output is left untouched and a
warning is printed (so a partial run still produces a valid PDF).

Usage:
    .venv/bin/python scripts/build_figure_data.py
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "paper" / "figures" / "data"


def build_ieee14() -> None:
    # Prefer the 10-seed multi-case dump (case14_edges.csv); fall back to old name.
    csv_path = DATA / "case14_edges.csv"
    if not csv_path.exists():
        csv_path = DATA / "ieee14_edges.csv"
    if not csv_path.exists():
        print(f"  [skip] no case14_edges.csv or ieee14_edges.csv — run dump_ieee14_edge_ranking.py first")
        return

    rows = []
    with csv_path.open() as f:
        for r in csv.DictReader(f):
            rows.append({
                "u": int(r["u"]),
                "v": int(r["v"]),
                "aegis": float(r["aegis_score_mean"]),
                "n1": float(r["n1_severity_mean"]),
                "a_rank": float(r["aegis_rank_mean"]),
                "n_rank": float(r["n1_rank_mean"]),
            })

    rows.sort(key=lambda r: r["a_rank"])
    top10_aegis = {(r["u"], r["v"]) for r in rows[:10]}
    by_n1 = sorted(rows, key=lambda r: r["n_rank"])
    top10_n1 = {(r["u"], r["v"]) for r in by_n1[:10]}

    out = []
    out.append("% AUTO-GENERATED by scripts/build_figure_data.py — do not edit by hand.")
    out.append(f"% Source: {csv_path.relative_to(ROOT)}")
    out.append(f"% Top-10 AEGIS edges; {len(top10_aegis & top10_n1)} of them are also in N-1 ground-truth top-10.")
    out.append("")
    out.append("% AEGIS top-10 edges (green-bold); dashed yellow overlay when also in N-1 GT top-10.")
    for r in rows[:10]:
        u, v = r["u"], r["v"]
        match = (u, v) in top10_n1
        style = "lineCritMatch" if match else "lineCrit"
        out.append(f"\\draw[{style}] (B{u}) -- (B{v});  % aegis_rank={r['a_rank']:.1f} n1_rank={r['n_rank']:.1f}")
    out.append("")
    p_at_10 = len(top10_aegis & top10_n1) / 10.0
    out.append(f"\\newcommand{{\\ieeefourteenPatTen}}{{{p_at_10:.2f}}}")

    out_path = DATA / "ieee14_top_edges.tex"
    out_path.write_text("\n".join(out) + "\n")
    print(f"  [ok]   wrote {out_path.relative_to(ROOT)}  ({len(rows)} edges, P@10={p_at_10:.2f})")


def build_sc_heatmap() -> None:
    sc_path = DATA / "sc_matrix.npy"
    if not sc_path.exists():
        print(f"  [skip] {sc_path.name} not found — run dump_sc_matrix_cora.py first")
        return

    sc = np.load(sc_path)  # shape (D, |E|)
    D, E = sc.shape

    # Display grid: prefer landscape (cols >= rows). Cap at 28 cols, 14 rows.
    max_cols = min(28, E)
    max_rows = 14

    # Columns: keep as-is if E <= max_cols, else uniformly sample
    if E <= max_cols:
        col_idx = np.arange(E)
    else:
        col_idx = np.linspace(0, E - 1, max_cols).astype(int)

    # Rows: mean-pool down to max_rows (preserves intensity better than striding)
    if D <= max_rows:
        sc_rows = sc
    else:
        group_size = D // max_rows
        trimmed = sc[: group_size * max_rows]
        sc_rows = trimmed.reshape(max_rows, group_size, E).mean(axis=1)

    sc_view = sc_rows[:, col_idx]
    sc_norm = sc_view / max(sc_view.max(), 1e-12)

    rows, cols = sc_norm.shape
    out = []
    out.append("% AUTO-GENERATED by scripts/build_figure_data.py — do not edit by hand.")
    out.append(f"% Source: {sc_path.relative_to(ROOT)}  (downsampled {D}x{E} -> {rows}x{cols})")
    out.append(f"\\def\\schmRows{{{rows-1}}}")
    out.append(f"\\def\\schmCols{{{cols-1}}}")
    out.append("")
    for r in range(rows):
        for c in range(cols):
            out.append(f"\\heatcell{{{c}}}{{{r}}}{{{sc_norm[r, c]:.3f}}}")

    out_path = DATA / "sc_heatmap_cells.tex"
    out_path.write_text("\n".join(out) + "\n")
    print(f"  [ok]   wrote {out_path.relative_to(ROOT)}  ({rows}x{cols} cells)")

    # ---- v_1 bars (aligned to the same column indices as the heatmap) ----
    v1_path = DATA / "sc_v1.npy"
    if v1_path.exists():
        v1 = np.load(v1_path)
        # Use the SAME column subsampling as the heatmap so bars line up below cells
        v1_view = v1[col_idx]
        v1_norm = v1_view / max(v1_view.max(), 1e-12)

        out2 = []
        out2.append("% AUTO-GENERATED by scripts/build_figure_data.py — do not edit by hand.")
        out2.append(f"% Source: {v1_path.relative_to(ROOT)}  ({len(v1)} edges; "
                    f"sampled to {len(v1_norm)} for display)")
        vals = ", ".join(f"{x:.3f}" for x in v1_norm)
        out2.append(f"\\def\\vonelist{{{{{vals}}}}}")
        out2.append(f"\\def\\voneCount{{{len(v1_norm)-1}}}")
        # Identify the top-2 indices in the DISPLAYED set for highlighting
        top2 = np.argsort(-v1_norm)[:2].tolist()
        out2.append(f"\\def\\voneHighA{{{top2[0]}}}")
        out2.append(f"\\def\\voneHighB{{{top2[1] if len(top2) > 1 else top2[0]}}}")
        # Concentration metric: how much mass is in the top-3 (real, not downsampled)
        v1_full_norm = v1 / max(v1.max(), 1e-12)
        top3_mass = float(np.sort(v1_full_norm ** 2)[-3:].sum() / max((v1_full_norm ** 2).sum(), 1e-12))
        out2.append(f"\\newcommand{{\\schmTopThreeMass}}{{{top3_mass:.2f}}}")
        out_v1 = DATA / "sc_v1_bars.tex"
        out_v1.write_text("\n".join(out2) + "\n")
        print(f"  [ok]   wrote {out_v1.relative_to(ROOT)}  ({len(v1_norm)} bars, "
              f"top2={top2}, top3 mass={top3_mass:.2f})")

    # ---- meta macros ----
    meta_json = DATA / "sc_meta.json"
    if meta_json.exists():
        meta = json.loads(meta_json.read_text())
        out3 = []
        out3.append("% AUTO-GENERATED by scripts/build_figure_data.py — do not edit by hand.")
        out3.append(f"\\newcommand{{\\schmN}}{{{meta['N_sub']}}}")
        out3.append(f"\\newcommand{{\\schmDim}}{{{meta['hidden']}}}")
        out3.append(f"\\newcommand{{\\schmEdges}}{{{meta['n_edges']}}}")
        out3.append(f"\\newcommand{{\\schmSigmaOne}}{{{meta['sigma_1']:.3f}}}")
        out3.append(f"\\newcommand{{\\schmGap}}{{{meta['gap_ratio']:.2f}}}")
        out_meta = DATA / "sc_meta.tex"
        out_meta.write_text("\n".join(out3) + "\n")
        print(f"  [ok]   wrote {out_meta.relative_to(ROOT)}  (sigma_1={meta['sigma_1']:.3f})")


def main():
    DATA.mkdir(parents=True, exist_ok=True)
    print(f"Building figure data fragments in {DATA.relative_to(ROOT)}/\n")
    print("IEEE 14-bus edge ranking:")
    build_ieee14()
    print()
    print("Cora S_c heatmap:")
    build_sc_heatmap()
    print()
    print("Done. Re-compile paper/aegis.tex to refresh figures.")


if __name__ == "__main__":
    sys.exit(main() or 0)
