"""Render paper/figures/fig_fraud_case.tex from paper/figures/data/fraud_case.json.

Icon node-link diagram of a fraud ego-subgraph with AEGIS's adversarial fault
lines: account icons (benign / fraud / audited-target), top-k edges by the
edge-weighted A_ij*v_ij in green with rank tags, and a match-marker on edges
also in the brute-force single-edge-removal damage top-k. Icons live in
paper/figures/icons/*.pdf. Edges are drawn first (explicit coords) so the
opaque icon nodes sit cleanly on top.

Usage:
    .venv/bin/python scripts/render_fraud_case_tikz.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
TOP_GREEN = 5   # edges drawn green (AEGIS top-k by edge-weighted score)
TOP_TAG = 3     # edges given an explicit rank tag
TOP_MATCH = 3   # discrete-damage top-k used for the brute-force-match marker
W, H = 8.4, 6.2  # layout box (cm) -- gives the icon nodes room to breathe

HEADER = r"""% AUTO-GENERATED by scripts/render_fraud_case_tikz.py -- do not edit by hand.
\documentclass[tikz,border=4pt,11pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{mathptmx}
\usepackage{tikz}
\usetikzlibrary{calc, decorations.markings}
\usepackage{graphicx}
\usepackage{xcolor}
\usepackage{amsmath, amssymb}
\usepackage{xspace}
\newcommand{\AEGIS}{\textsc{Aegis}\xspace}
\renewcommand{\familydefault}{\rmdefault}

\definecolor{okBlue}{HTML}{0072B2}
\definecolor{okGreen}{HTML}{009E73}
\definecolor{okVermilion}{HTML}{D55E00}
\definecolor{okYellow}{HTML}{F0E442}
\definecolor{okGrey}{HTML}{888888}
\colorlet{cfraud}{okVermilion}
\colorlet{cbenign}{okBlue}
\colorlet{ccrit}{okGreen}
\colorlet{cnorm}{okGrey!50}
\colorlet{cmatch}{okYellow!90!black}

\tikzset{
  iconF/.style={circle, draw=cfraud!80!black, line width=1.0pt, fill=white, inner sep=0.4pt},
  iconB/.style={circle, draw=cbenign!80!black, line width=1.0pt, fill=white, inner sep=0.4pt},
  iconT/.style={circle, draw=cfraud!75!black, line width=1.7pt, fill=white, inner sep=0.4pt},
  eNorm/.style={draw=cnorm, line width=0.8pt},
  eCrit/.style={draw=ccrit!85!black, line width=2.0pt},
  eCritMatch/.style={draw=ccrit!85!black, line width=2.0pt,
    postaction={decorate, decoration={markings, mark=at position 0.5 with {
      \node[circle, fill=cmatch, draw=cmatch!40!black, inner sep=0pt,
            minimum size=2.0mm, line width=0.3pt] {};}}}},
  rankTag/.style={font=\small\bfseries, color=ccrit!45!black, fill=white,
    fill opacity=0.92, text opacity=1, inner sep=1.2pt, rounded corners=1pt,
    draw=ccrit!45!black, line width=0.25pt},
}
\begin{document}
\begin{tikzpicture}[x=1cm, y=1cm]
"""


def main():
    data = json.loads((ROOT / "paper/figures/data/fraud_case.json").read_text())
    nodes = data["nodes"]
    edges = data["edges"]
    tgt = data["target_local"]
    n_fraud = sum(1 for n in nodes if n["label"] == 1)
    tau_w = data["tau_weighted_vs_dk"]

    xs = np.array([n["x"] for n in nodes]); ys = np.array([n["y"] for n in nodes])
    xs = (xs - xs.min()) / (xs.max() - xs.min() + 1e-9) * W
    ys = (ys - ys.min()) / (ys.max() - ys.min() + 1e-9) * H
    coord = {n["local"]: (float(xs[k]), float(ys[k])) for k, n in enumerate(nodes)}

    def C(k):
        x, y = coord[k]
        return f"({x:.2f},{y:.2f})"

    by_rank = sorted(edges, key=lambda e: e["rank"])
    dmg_top = set(sorted(range(len(edges)), key=lambda i: -edges[i]["d_k"])[:TOP_MATCH])
    green = {e["rank"]: e for e in by_rank if e["rank"] <= TOP_GREEN}

    L = [HEADER]

    # ---- edges first (explicit coords) so the opaque icon nodes sit on top ----
    L.append("% ---- normal (grey) edges ----")
    for e in edges:
        if e["rank"] > TOP_GREEN:
            L.append(f"\\draw[eNorm] {C(e['u'])} -- {C(e['v'])};")
    L.append("% ---- AEGIS top-k edges (green; +dot if in brute-force damage top-k) ----")
    for ei, e in enumerate(edges):
        if e["rank"] <= TOP_GREEN:
            sty = "eCritMatch" if ei in dmg_top else "eCrit"
            L.append(f"\\draw[{sty}] {C(e['u'])} -- {C(e['v'])};")

    # ---- account icon nodes on top ----
    L.append("% ---- account icon nodes ----")
    for n in nodes:
        x, y = coord[n["local"]]
        if n["local"] == tgt:
            L.append(f"\\node[iconT, minimum size=9.6mm] at ({x:.2f},{y:.2f}) "
                     f"{{\\includegraphics[width=8.6mm]{{icons/target}}}};")
        else:
            ic, sty = ("fraud", "iconF") if n["label"] == 1 else ("benign", "iconB")
            L.append(f"\\node[{sty}, minimum size=7.6mm] at ({x:.2f},{y:.2f}) "
                     f"{{\\includegraphics[width=6.8mm]{{icons/{ic}}}}};")

    # ---- rank tags (nudged off the midpoint so the match-dot shows) ----
    L.append("% ---- rank tags ----")
    for r in range(1, TOP_TAG + 1):
        e = green.get(r)
        if e is None:
            continue
        xu, yu = coord[e["u"]]; xv, yv = coord[e["v"]]
        dx, dy = xv - xu, yv - yu
        seg = (dx * dx + dy * dy) ** 0.5 or 1.0
        ox = (xu + xv) / 2 - 0.46 * dy / seg
        oy = (yu + yv) / 2 + 0.46 * dx / seg
        L.append(f"\\node[rankTag] at ({ox:.2f},{oy:.2f}) {{\\#{r}}};")

    # ---- legend ----
    L.append(rf"""% ---- legend ----
\begin{{scope}}[shift={{({W + 1.15:.2f}, {H + 0.2:.2f})}}]
  \node[font=\normalsize\itshape, color=black!65, anchor=west] at (-0.30, 0.52) {{Accounts}};
  \node[iconT, minimum size=6.2mm] at (0,-0.22) {{\includegraphics[width=5.4mm]{{icons/target}}}};
  \node[font=\small, anchor=west, black] at (0.50,-0.22) {{Audited Fraud Account}};
  \node[iconF, minimum size=5.6mm] at (0,-0.92) {{\includegraphics[width=4.9mm]{{icons/fraud}}}};
  \node[font=\small, anchor=west, black] at (0.50,-0.92) {{Fraud}};
  \node[iconB, minimum size=5.6mm] at (0,-1.55) {{\includegraphics[width=4.9mm]{{icons/benign}}}};
  \node[font=\small, anchor=west, black] at (0.50,-1.55) {{Benign}};
  \node[font=\normalsize\itshape, color=black!65, anchor=west] at (-0.30, -2.20) {{Edges}};
  \draw[eCrit] (-0.25,-2.66) -- (0.25,-2.66) node[right=3pt, font=\small, black] {{\AEGIS{{}} Top-5}};
  \draw[eCrit] (-0.25,-3.22) -- (0.25,-3.22);
  \node[circle, fill=cmatch, draw=cmatch!40!black, inner sep=0pt, minimum size=2.0mm,
        line width=0.3pt] at (0,-3.22) {{}};
  \node[font=\small, anchor=west, black] at (0.32,-3.22) {{Also Brute-Force Top-3}};
  \draw[eNorm] (-0.25,-3.78) -- (0.25,-3.78) node[right=3pt, font=\small, black] {{Other Edges}};
  \node[font=\normalsize\itshape, color=black!65, anchor=west] at (-0.30, -4.40) {{Rank}};
  \node[rankTag] at (0,-4.86) {{\#k}};
  \node[font=\small, anchor=west, black] at (0.32,-4.86) {{$A_{{ij}}v_{{ij}}$ Rank}};
\end{{scope}}""")

    # ---- summary card (with review-02 accent) ----
    L.append(r"\node[anchor=north west, font=\small, draw=okGrey!35, line width=0.3pt,")
    L.append(r"      fill=white, rounded corners=2pt, inner sep=4pt, align=left]")
    L.append(f"  at (-0.4, -0.55) {{\\raisebox{{-2.4mm}}{{\\includegraphics[width=7mm]{{icons/review-02}}}}~"
             f"\\textbf{{Amazon Fraud}}\\, \\textcolor{{black!55}}{{(11{{,}}944 accounts; "
             f"{data['n_nodes']}-node fraud cluster, {n_fraud} fraud)}}\\\\")
    L.append(r"   one \AEGIS{} query: top edges by $A_{ij}v_{ij}$ match brute-force removal "
             f"(\\textbf{{$\\tau{{=}}{tau_w:.2f}$}})}};")

    L.append(r"\end{tikzpicture}")
    L.append(r"\end{document}")

    out = ROOT / "paper/figures/fig_fraud_case.tex"
    out.write_text("\n".join(L) + "\n")
    print(f"nodes={len(nodes)} ({n_fraud} fraud, {len(nodes)-n_fraud} benign)  edges={len(edges)}  "
          f"target_local={tgt}  tau_w={tau_w:+.2f}")
    print("green edges:", [(e["rank"], e["u"], e["v"], edges.index(e) in dmg_top) for e in by_rank[:TOP_GREEN]])
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
